import React from "react";
import PropTypes from "prop-types";
import { Icon } from "@shopify/polaris";

const IconMerge = props => {
  return <Icon {...props} />;
};

IconMerge.propTypes = {
  backdrop: PropTypes.bool,
  color: PropTypes.oneOf([
    "white",
    "black",
    "skyLighter",
    "skyLight",
    "sky",
    "skyDark",
    "inkLightest",
    "inkLighter",
    "inkLight",
    "ink",
    "blueLighter",
    "blueLight",
    "blue",
    "blueDark",
    "blueDarker",
    "indigoLighter",
    "indigoLight",
    "indigo",
    "indigoDark",
    "indigoDarker",
    "tealLighter",
    "tealLight",
    "teal",
    "tealDark",
    "tealDarker",
    "greenLighter",
    "green",
    "greenDark",
    "yellowLighter",
    "yellow",
    "yellowDark",
    "yellow",
    "orange",
    "redLighter",
    "red",
    "redDark",
    "purple"
  ]),
  source: PropTypes.oneOf([
    "add",
    "alert",
    "arrowDown",
    "arrowLeft",
    "arrowRight",
    "arrowUp",
    "arrowUpDown",
    "calendar",
    "cancel",
    "cancelSmall",
    "caretDown",
    "caretUp",
    "checkmark",
    "chevronDown",
    "chevronLeft",
    "chevronRight",
    "chevronUp",
    "circleCancel",
    "circleChevronDown",
    "circleChevronLeft",
    "circleChevronRight",
    "circleChevronUp",
    "circleInformation",
    "circlePlus",
    "circlePlusOutline",
    "conversation",
    "delete",
    "disable",
    "dispute",
    "duplicate",
    "embed",
    "export",
    "external",
    "help",
    "home",
    "horizontalDots",
    "import",
    "logOut",
    "notes",
    "notification",
    "onlineStore",
    "orders",
    "print",
    "products",
    "profile",
    "refresh",
    "risk",
    "save",
    "search",
    "subtract",
    "view"
  ])
};

export { IconMerge as default };
